# Generated by Django 3.2.14 on 2022-07-23 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_compromisso', models.CharField(max_length=120, verbose_name='Nome do compromisso')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_termino', models.TimeField(verbose_name='Hora de término')),
                ('local', models.CharField(max_length=120, verbose_name='Local')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status_compromisso', models.CharField(choices=[('A', 'Agendado'), ('C', 'Cancelado'), ('R', 'Realizado')], default='A', max_length=1, verbose_name='Status do compromisso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'db_table': 'compromissos',
            },
        ),
    ]
